### ISSUE TITLE
Ajout de Reaper

### ISSUE THREAD

**Issue by zerojardins** [randomDam/memo_cmd#1]
**Reaper**
Alternative à Pro-Tools de première classe.
Fonctionne parfaitement avec Wine ET existe en version native depuis peu.

Ce n'est pas un logiciel libre, mais il fonctionne parfaitement et complètement même si on n'achète pas la licence.

[https://www.reaper.fm/download.php](https://www.reaper.fm/download.php)

**Comment by randomDam** [comment]
Validé, ajouté et PDF régénéré.
